#' Lattice plot of conditional densities
#'
#' This function produces conditional density plots at input covariate values.
#' @param X the covariate matrix to predict conditional densities at; each row represents an observation vector.
#' @param minY the minimal possible response value. If \code{yGrid} is NULL, then the response grid will be generated by dividing \code{(minY, maxY)} into \code{nGrid} equal bins and using the mid-points as \code{yGrid}. Default is NULL.
#' @param maxY the maximal possible response value. For more, see \code{minY}. Default is NULL.
#' @param nGrid the number of response grid points. For more, see \code{minY}. Default is 100.
#' @param yGrid the response grid to evaluate conditional densities at. Default is NULL.
#' @param model a conditional density model with a \code{predict} method, e.g., a LinCDE boosting model. The call \code{predict(model, X, y)} should return a vector of estimated conditional densities f(yi | Xi). To only plot the true conditional densities, leave the \code{model} blank. Default is NULL.
#' @param trueDensity true conditional density function. The call \code{trueDensity(X, y)} should return a vector of true conditional densities f(yi | Xi). To only plot LinCDE's estimated conditional densities, leave the \code{trueDensity} blank. Default is NULL.
#'
#' @return The function outputs a lattice plot of conditional densities.
#' @export
densityPlot = function(X, minY = NULL, maxY = NULL, nGrid = 100, yGrid = NULL,  model = NULL, trueDensity = NULL){
  # preprocess
  if(is.null(dim(X))){X = matrix(X, nrow = 1)}
  n = dim(X)[1]; d = dim(X)[2]
  XGrid = X[rep(seq(1,n), rep(nGrid, n)), ]
  if(is.null(yGrid)){
    if(is.null(model) && (is.null(minY)||is.null(maxY))){stop("please input the a grid or the range of responses")}
    if(is.null(minY)){minY = 1.02 * min(model$y) - 0.02 * max(model$y)}
    if(is.null(maxY)){maxY = 1.02 * max(model$y) - 0.02 * min(model$y)}
    yGrid = seq(minY, maxY, length.out = (nGrid+1))
    yGrid = (yGrid[1:nGrid] + yGrid[2:(nGrid+1)])/2
  }
  nGrid = length(yGrid); yGrid = rep(yGrid, n)

  # lattice plot of the true and estimated densities
  if(!is.null(trueDensity) && !is.null(model)){
    trueDens = trueDensity(XGrid, yGrid)
    h = model$splitMidPointY[2] - model$splitMidPointY[1]
    splitPointYTest = seq(model$splitMidPointY[1] - h/2, tail(model$splitMidPointY,n=1) + h/2, length.out = 2 * nGrid)
    estDens = predict(object = model, X = XGrid, y = yGrid, splitPointYTest = splitPointYTest)

    latticeCDE = data.frame(rep(yGrid, 2)); colnames(latticeCDE) = "y"
    latticeCDE$density = c(trueDens, estDens)
    latticeCDE$method = factor(c(rep(c("truth", "estimated"), rep(nGrid * n,2))), levels=c("truth", "estimated"))
    latticeCDE$group = rep(rep(seq(1,n), rep(nGrid,n)), 2)
    key=list(space="top", columns = 2,
             lines=list(col=c("blue", "red"), lty=c(3,1), lwd=3),
             text=list(c("truth", "estimated")), cex = 1)
    strip = lattice::strip.custom(bg="lightgrey", factor.levels = paste("R", seq(1,n)), par.strip.text=list(col="black", cex=0.8, font=1))
    plot = lattice::xyplot(density ~ y | factor(group), group = latticeCDE$method, data = latticeCDE, type = "l", col = c("blue", "red"), lty = c(3,1), lwd = 3, ylab=list("conditional density", cex = 1), xlab = list("y", cex = 1), key = key, aspect = 0.75, layout = c(floor(sqrt(n)),ceiling(n/floor(sqrt(n)))), strip = strip, scales = list(cex = 1), main = "Estimated and true conditional densities")
  }

  # lattice plot of the true densities
  if(!is.null(trueDensity) && is.null(model)){
    trueDens = trueDensity(XGrid, yGrid)

    latticeCDE = data.frame(yGrid); colnames(latticeCDE) = "y"
    latticeCDE$density = trueDens
    latticeCDE$group = rep(seq(1,n), rep(nGrid,n))
    strip = lattice::strip.custom(bg="lightgrey", factor.levels = paste("R", seq(1,n)), par.strip.text=list(col="black", cex=0.8, font=1))
    plot = lattice::xyplot(density ~ y | factor(group), data = latticeCDE, type = "l", col = c("blue"), lty = 3, lwd = 3, ylab=list("conditional density", cex = 1), xlab = list("y", cex = 1), aspect = 0.75, layout = c(floor(sqrt(n)),ceiling(n/floor(sqrt(n)))), strip = strip, scales = list(cex = 1), main = "True conditional densities")
  }

  # lattice plot of the estimated densities
  if(is.null(trueDensity) && !is.null(model)){
    h = model$splitMidPointY[2] - model$splitMidPointY[1]
    splitPointYTest = seq(model$splitMidPointY[1] - h/2, tail(model$splitMidPointY,n=1) + h/2, length.out = 2 * nGrid)
    estDens = predict(object = model, X = XGrid, y = yGrid, splitPointYTest = splitPointYTest)

    latticeCDE = data.frame(yGrid); colnames(latticeCDE) = "y"
    latticeCDE$density = c(estDens)
    latticeCDE$group = rep(seq(1,n), rep(nGrid,n))
    strip = lattice::strip.custom(bg="lightgrey", factor.levels = paste("R", seq(1,n)), par.strip.text=list(col="black", cex=0.8, font=1))
    plot = lattice::xyplot(density ~ y | factor(group), data = latticeCDE, type = "l", col = c("red"), lty = 1, lwd = 3, ylab=list("conditional density", cex = 1), xlab = list("y", cex = 1), aspect = 0.75, layout = c(floor(sqrt(n)),ceiling(n/floor(sqrt(n)))), strip = strip, scales = list(cex = 1), main = "Estimated conditional densities")
  }
  print(plot)
}
