# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LinCDECdf <- function(cellProb, y, splitPointY) {
    .Call(`_LinCDE_LinCDECdf`, cellProb, y, splitPointY)
}

LinCDEQuantiles <- function(cellProb, probs, splitPointY) {
    .Call(`_LinCDE_LinCDEQuantiles`, cellProb, probs, splitPointY)
}

LinCDESplit <- function(X, yIndex, cellProb, z, covMatrixInv, splitPoint, numberBin) {
    .Call(`_LinCDE_LinCDESplit`, X, yIndex, cellProb, z, covMatrixInv, splitPoint, numberBin)
}

rcpp_hello_world <- function() {
    .Call(`_LinCDE_rcpp_hello_world`)
}

